### ISSUE TITLE
Allow to choose time zone

### ISSUE THREAD

**Issue by mnoblecourt** [CartONG/mapathon_dashboard#12]
Currently I'm not sure who the time zone is defined in the dashboard (CET? local based on computer's time?) but it would be useful to be able to choose, or at least to display which time zone is being used to run the calculation.

**Comment by regazzoj** [comment]
Complement : The time zone defined in the dashboard is the system local time.
BUT whatever the zone of the computer is, the time zone used to run the calculation is the UTC zone.

**Comment by regazzoj** [comment]
For now, we display the UTC zone used.
BUT whatever the zone of the computer is, the time zone used to run the calculation is the UTC zone.
