### ISSUE TITLE
Update the mapathon Dashboard to the new Tasking Manager API

### ISSUE THREAD

**Issue by NicolasGrosjean** [CartONG/mapathon_dashboard#21]
The dashboard use this url : https://tasks.hotosm.org/api/v1/project/XXX/summary

The new url : https://tasking-manager-tm4-production-api.hotosm.org/api/v2/projects/XXX/queries/summary

![image](https://user-images.githubusercontent.com/13560473/81596505-81df7580-93c4-11ea-96b1-d2b605d2a3d3.png)

**Comment by regazzoj** [comment]
Hello Nicolas,

I resolved your issue in my last commit on master branch.
But for now, this branch has not be pushed to the website.

Thanks for your help !
