### ISSUE TITLE
Choose tasking manager instance

### ISSUE THREAD

**Issue by ViolaineDo** [CartONG/mapathon_dashboard#3]
Enabling users to pick stats from other tasking manager instances

**Comment by LorenzoStucchi** [comment]
@ViolaineDo you can fork it and adapt for the tasking manager that you need, I did it for TeachOSM for a monitoring a mapathon that I have done. You can find it at https://lorenzostucchi.github.io/mapathon_dashboard/

**Comment by ViolaineDo** [comment]
@LorenzoStucchi Awesome that you deployed it for your tasking manager instance!! I was wondering if it would be easy to do. Actually I was suggesting that, as I thought it would be of interest for some other actors like you, but no operational need my end. I was actually helping the development at the start, giving our needs to developpers... so this is it! Thanks so much for your feedback. I think @joamartin and dev team behind this will be happy to know it was used / duplicated

**Comment by LorenzoStucchi** [comment]
@ViolaineDo Thanks! It's simple to adapt it to other tasking managers, there are just few links to be changed. For me, this should be directly integrated with all the tasking managers.
