### ISSUE TITLE
Tag depends on Tasking Manager

### ISSUE THREAD

**Issue by regazzoj** [CartONG/mapathon_dashboard#32]
Until now, whatever tasking manager chosen, changesets were filtered according to an unique tag, the one for HOTOSM.
The task is to find and use the correct tag for every TM.
TM without tag :
- OSM Earth
- OSM Paraguay
- OSM Colombia
- OSM Colorado
- OSM USA
- OSM Portugal

TM with tag :
- HOTOSM => hotosm-project
- OSM Italy => osmitaly
- teachOSM => teachosm-task

**Comment by LorenzoStucchi** [comment]
* OSM Earth => osmearth
* OSM Paraguay => Not an unique hashtag
* OSM Colombia => osmco-project
* OSM Colorado => osmco-project
* OSM USA => osmus-tasks
* OSM Portugal => Not an unique hashtag

For Colorado and Colombia, the hashtag is the same 😲

**Comment by regazzoj** [comment]
Thanks @LorenzoStucchi ! I will fix this tonight.
Did my last commit fix your issue ?
And how did you find these tags ?

**Comment by LorenzoStucchi** [comment]
> Did my last commit fix your issue ?

I check it now and works, thank to you 😊 

> And how did you find these tags ?

I check in the information box inside different projects of each tasking manager and it is generally composed as the hashtag a hyphen and the number of the project.
Like #osmus-tasks-76 see [OSMCha](https://osmcha.org/?filters={"in_bbox"%3A[{"label"%3A"-106.231766950382%2C40.3543419630175%2C-105.145088640102%2C40.9969993071255"%2C"value"%3A"-106.231766950382%2C40.3543419630175%2C-105.145088640102%2C40.9969993071255"}]%2C"area_lt"%3A[{"label"%3A2%2C"value"%3A2}]%2C"date__gte"%3A[{"label"%3A"2020-09-08"%2C"value"%3A"2020-09-08"}]%2C"comment"%3A[{"label"%3A"%23osmus-tasks-216"%2C"value"%3A"%23osmus-tasks-216"}]}) or at the end of the page of the [project](https://tasks.openstreetmap.us/projects/216/tasks) in the Instruction panel.
