### ISSUE TITLE
Enable dynamic inteactions

### ISSUE THREAD

**Issue by ViolaineDo** [CartONG/mapathon_dashboard#5]
For ex. when clicking on the building statistics, it would be great to see buidlings only on the vizualisation map.

**Comment by mnoblecourt** [comment]
Sur la carte de prévisualisation des données, afficher uniquement un type d'objet (routes, bâtiments, zones résidentielles), p. ex. en cliquant sur le "bloc" correspondant de statistiques sur la page. Non prioritaire.
